name: Regression Test

on: [push, pull_request]

jobs:
  regresstion_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run the test
      run: |
        pip install coverage
        coverage run runTest.py
        coverage xml
        bash <(curl -s https://codecov.io/bash)
